---
ubuntu_codename: "noble"
k8s_version: "1.35.6"
helm_version: "3.17.2"
helm_diff_version: "3.4.1"
pod_cidr: "10.244.0.0/16"
control_plane_port: "6443"
iface: "eth0"
kubeconfig_path: /etc/kubernetes/admin.conf
manifests_dir: /opt/manifests
control_plane_vip: "10.10.10.30"
control_plane_endpoint: "{{ control_plane_vip }}:{{ control_plane_port }}"
keepalived_enabled: false
### MIRRORS
repo_mirror: "mirror.yandex.ru" # OS repo mirror
docker_repo_mirror: "download.docker.com" #download.docker.com
k8s_repo_mirror: "{{ repo_mirror }}/mirrors/pkgs.k8s.io" # "pkgs.k8s.io"
docker_registry_mirrors:
  - "https://mirror.gcr.io"
  - "https://dockerhub.timeweb.cloud"
k8s_image_repo: "registry.aliyuncs.com/google_containers" # registry.k8s.io
docker_image_repo: "dockerhub.timeweb.cloud" # docker.io
quay_image_repo: "quay.m.daocloud.io" # quay.io
### CILIUM
cilium_version: "1.19.3"
cilium_envoy_version: "1.36.6-1776000132-2437d2edeaf4d9b56ef279bd0d71127440c067aa"
cilium_rollout_timeout: "600s"
cilium_hubble_enabled: false
cilium_l2_announcements_enabled: true
cilium_k8s_client_rate_limit_qps: 10
cilium_k8s_client_rate_limit_burst: 20
cilium_lb_mode: "dedicated" # shared | dedicated | tunneled
cilium_lb_ip_pool_name: lb-pool-default
cilium_lb_ip_pool_start: "10.10.10.200"
cilium_lb_ip_pool_stop: "10.10.10.220"
cilium_l2_announcement_policy_name: lb-pool-l2
cilium_l2_interfaces:
  - "{{ iface }}"
### CILIUM IMAGES
cilium_image: "{{ docker_image_repo }}/rancher/mirrored-cilium-cilium" # quay.io/cilium/cilium
cilium_envoy_image: "{{ docker_image_repo }}/rancher/mirrored-cilium-cilium-envoy" # quay.io/cilium/cilium-envoy
cilium_operator_image: "{{ docker_image_repo }}/rancher/mirrored-cilium-operator" # quay.io/cilium/operator
# cilium_hubble_image: "{{ docker_image_repo }}/rancher/mirrored-cilium-hubble" # quay.io/cilium/hubble
# cilium_hubble_relay_image: "{{ docker_image_repo }}/rancher/mirrored-cilium-hubble-relay" # quay.io/cilium/hubble-relay
# cilium_hubble_ui_image: "{{ docker_image_repo }}/rancher/mirrored-cilium-hubble-ui" # quay.io/cilium/hubble-ui
# cilium_hubble_ui_backend_image: "{{ docker_image_repo }}/rancher/mirrored-cilium-hubble-ui-backend" # quay.io/cilium/hubble-ui-backend
# cilium_hubble_ui_frontend_image: "{{ docker_image_repo }}/rancher/mirrored-cilium-hubble-ui-frontend" # quay.io/cilium/hubble-ui-frontend
# cilium_hubble_ui_frontend_image: "{{ docker_image_repo }}/rancher/mirrored-cilium-hubble-ui-frontend" # quay.io/cilium/hubble-ui-frontend
### LONGHORN
longhorn_version: "1.12.0"
longhorn_namespace: longhorn-system
longhorn_rollout_timeout: "600s"
longhorn_trim_recurring_job_enabled: true
longhorn_trim_recurring_job_name: trim
longhorn_trim_recurring_job_display_name: Trim
longhorn_trim_recurring_job_cron: "0 */3 * * *"
longhorn_trim_recurring_job_groups:
  - default
longhorn_trim_recurring_job_concurrency: 1
longhorn_trim_recurring_job_retain: 0
### CERT-MANAGER
cert_manager_version: "v1.17.2"
cert_manager_namespace: cert-manager
cert_manager_rollout_timeout: "300s"
cert_manager_image_repo: "{{ quay_image_repo }}"
### CLOUDNATIVEPG
cloudnativepg_version: "0.28.3"
cloudnativepg_namespace: cnpg-system
cloudnativepg_rollout_timeout: "300s"
