---
ubuntu_codename: "noble"
k8s_version: "1.35.4"
k8s_minor: "{{ k8s_version.split('.')[:2] | join('.') }}"
pod_cidr: "10.244.0.0/16"
control_plane_port: "6443"
control_plane_endpoint: "{{ hostvars[groups['master'][0]].ansible_host }}:{{ control_plane_port }}"
repo_mirror: "mirror.yandex.ru"
docker_repo_mirror: "{{ repo_mirror }}/mirrors/download.docker.com"
docker_registry_mirrors:
  - "https://mirror.gcr.io"
  - "https://dockerhub.timeweb.cloud"
k8s_image_repo: "registry.aliyuncs.com/google_containers"
quay_image_repo: "quay.m.daocloud.io"