[master]
master-1 ansible_host=10.10.10.30
master-2 ansible_host=10.10.10.31
; master-3 ansible_host=10.10.10.32

[workers]
; worker-1 ansible_host=10.10.10.30
; worker-2 ansible_host=10.10.10.31
worker-3 ansible_host=10.10.10.32
