---
- name: Configure all hosts
  hosts: all
  become: true
  gather_facts: false
  roles:
    - common

- name: Initialize control-plane nodes
  hosts: master
  become: true
  gather_facts: false
  any_errors_fatal: true
  serial: 1
  roles:
    - init
    - join

- name: Join worker nodes
  hosts: workers
  become: true
  gather_facts: false
  any_errors_fatal: true
  serial: 1
  roles:
    - join

- name: Post-cluster configuration
  hosts: master
  become: true
  gather_facts: false
  roles:
    - post-cluster
