---
cilium_images:
  - "{{ cilium_image }}:v{{ cilium_version }}"
  - "{{ cilium_operator_image }}-generic:v{{ cilium_version }}"
  - "{{ cilium_envoy_image }}:v{{ cilium_envoy_version }}"

longhorn_packages:
  - open-iscsi
  - nfs-common
  - jq
  - curl
longhorn_kernel_modules:
  - iscsi_tcp
longhorn_services:
  - iscsid
  - open-iscsi
  - rpcbind
