---
- name: restart docker
  systemd:
    name: docker
    state: restarted

- name: restart containerd
  systemd:
    name: containerd
    state: restarted

- name: restart journald
  systemd:
    name: systemd-journald
    state: restarted