---
- name: Add Kubernetes GPG key
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v{{ k8s_minor }}/deb/Release.key
    keyring: /usr/share/keyrings/kubernetes-keyring.gpg

- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64 signed-by=/usr/share/keyrings/kubernetes-keyring.gpg]
      https://{{ repo_mirror }}/mirrors/pkgs.k8s.io/core/stable/v{{ k8s_minor }}/deb/ /
    state: present
    update_cache: true

- name: Install Kubernetes packages
  ansible.builtin.apt:
    name:
      - kubelet={{ k8s_version }}-1.1
      - kubeadm={{ k8s_version }}-1.1
      - kubectl={{ k8s_version }}-1.1
    state: present
    update_cache: true

- name: Hold Kubernetes packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
