---
- name: Fetch kubeconfig from master
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: /tmp/kubeconfig-cilium
    flat: true

- name: Add Cilium helm repo
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/
    kubeconfig: /tmp/kubeconfig-cilium
  delegate_to: localhost

- name: Install Cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    release_namespace: kube-system
    kubeconfig: /tmp/kubeconfig-cilium
    values:
      image:
        repository: "{{ image_repo }}/cilium/cilium"
      kubeProxyReplacement: true
      ingressController:
        enabled: true
        loadbalancerMode: dedicated
      envoy:
        enabled: true
  delegate_to: localhost

- name: Delete kube-proxy DaemonSet
  ansible.builtin.command: kubectl -n kube-system delete ds kube-proxy
  register: _init_delete_proxy
  failed_when:
    - _init_delete_proxy.rc != 0
    - '"not found" not in _init_delete_proxy.stderr'
  changed_when: _init_delete_proxy.rc == 0

- name: Remove temporary kubeconfig
  ansible.builtin.file:
    path: /tmp/kubeconfig-cilium
    state: absent
  delegate_to: localhost
