---
cilium_helm_values:
  kubeProxyReplacement: true
  ingressController:
    enabled: true
    loadbalancerMode: dedicated
  envoy:
    enabled: true
    image:
      repository: "{{ cilium_envoy_image }}"
      useDigest: false
  image:
    repository: "{{ cilium_image }}"
    useDigest: false
  operator:
    image:
      repository: "{{ cilium_operator_image }}"
      useDigest: false
  hubble:
    enabled: "{{ cilium_hubble_enabled }}"
  l2announcements:
    enabled: "{{ cilium_l2_announcements_enabled }}"
  k8sClientRateLimit:
    qps: "{{ cilium_k8s_client_rate_limit_qps }}"
    burst: "{{ cilium_k8s_client_rate_limit_burst }}"

longhorn_helm_values:
  global:
    imageRegistry: "{{ docker_image_repo }}"

cert_manager_helm_values:
  crds:
    enabled: true
  image:
    repository: "{{ cert_manager_image_repo }}/jetstack/cert-manager-controller"
  webhook:
    image:
      repository: "{{ cert_manager_image_repo }}/jetstack/cert-manager-webhook"
  cainjector:
    image:
      repository: "{{ cert_manager_image_repo }}/jetstack/cert-manager-cainjector"
  acmesolver:
    image:
      repository: "{{ cert_manager_image_repo }}/jetstack/cert-manager-acmesolver"
  startupapicheck:
    image:
      repository: "{{ cert_manager_image_repo }}/jetstack/cert-manager-startupapicheck"

cloudnativepg_helm_values: {}
